hex2pic.hex: hex2pic.o delay.o hexfile.o interrupt.o number.o uart.o
	gplink -o $@ hex2pic.o delay.o hexfile.o interrupt.o number.o uart.o

%.o: %.asm
	gpasm -p 16f887 -c -o $@ $<

clean:
	rm -f *.cod *.hex *.lst *.o
